import React, { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../components/ui/card';
import { Sparkles, TrendingUp, AlertTriangle, Lightbulb, Target } from 'lucide-react';
import { apiFetch } from '../lib/api';

export default function Insights() {
  const [insights, setInsights] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadInsights();
  }, []);

  const loadInsights = async () => {
    try {
      const data = await apiFetch('/insights');
      setInsights(data);
    } catch(e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const getIcon = (type: string) => {
    switch (type) {
      case 'risk': return <AlertTriangle className="h-5 w-5 text-red-500" />;
      case 'opportunity': return <TrendingUp className="h-5 w-5 text-emerald-500" />;
      case 'summary': return <Target className="h-5 w-5 text-indigo-500" />;
      case 'score': return <Lightbulb className="h-5 w-5 text-amber-500" />;
      default: return <Sparkles className="h-5 w-5 text-slate-500" />;
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500 max-w-6xl mx-auto">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-slate-900 flex items-center gap-3">
          <Sparkles className="h-8 w-8 text-indigo-600" />
          AI Insights & Analytics
        </h1>
        <p className="text-slate-500 mt-2">
          Autonomous recommendations, risk detection, and revenue intelligence generated by Aegix AI.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
         <Card className="border-slate-200 shadow-sm bg-gradient-to-br from-indigo-500 to-purple-600 text-white">
            <CardHeader className="pb-2">
               <CardTitle className="text-lg font-medium text-indigo-50">Revenue Forecast</CardTitle>
            </CardHeader>
            <CardContent>
               <div className="text-3xl font-bold">$1.2M</div>
               <p className="text-indigo-100 text-sm mt-1 opacity-90">+15% expected growth this quarter</p>
            </CardContent>
         </Card>
         <Card className="border-slate-200 shadow-sm bg-white">
            <CardHeader className="pb-2">
               <CardTitle className="text-lg font-medium text-slate-700">Pipeline Health</CardTitle>
            </CardHeader>
            <CardContent>
               <div className="text-3xl font-bold text-emerald-600">84/100</div>
               <p className="text-slate-500 text-sm mt-1">High conversion probability across stages</p>
            </CardContent>
         </Card>
         <Card className="border-slate-200 shadow-sm bg-white">
            <CardHeader className="pb-2">
               <CardTitle className="text-lg font-medium text-slate-700">Deals at Risk</CardTitle>
            </CardHeader>
            <CardContent>
               <div className="text-3xl font-bold text-red-500">3</div>
               <p className="text-slate-500 text-sm mt-1">Stagnant for &gt; 14 days without activity</p>
            </CardContent>
         </Card>
      </div>

      <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">Latest Recommendations</h2>
      
      {loading ? (
        <div className="space-y-4">
           {[1,2,3].map(i => <div key={i} className="h-24 bg-slate-100 rounded-xl animate-pulse"></div>)}
        </div>
      ) : insights.length === 0 ? (
        <Card className="border-dashed border-2 py-12">
            <CardContent className="flex flex-col items-center justify-center text-center space-y-4">
               <div className="h-16 w-16 bg-slate-50 rounded-full flex items-center justify-center">
                 <Sparkles className="h-8 w-8 text-slate-400" />
               </div>
               <h3 className="text-lg font-semibold text-slate-900">No insights generated yet</h3>
               <p className="text-sm text-slate-500 max-w-sm">Aegix AI continuously monitors your pipeline. Check back later for automated recommendations and risk assessments.</p>
            </CardContent>
         </Card>
      ) : (
        <div className="space-y-4">
           {insights.map(insight => (
             <Card key={insight.id} className="border-slate-200 shadow-sm hover:shadow transition">
               <CardContent className="p-5 flex items-start gap-4">
                 <div className={`p-2 rounded-xl mt-1 ${
                   insight.type === 'risk' ? 'bg-red-50' : 
                   insight.type === 'opportunity' ? 'bg-emerald-50' :
                   'bg-indigo-50'
                 }`}>
                   {getIcon(insight.type)}
                 </div>
                 <div className="flex-1 space-y-1">
                   <div className="flex items-center justify-between">
                     <h3 className="font-semibold text-slate-900 capitalize">{insight.type} Detected</h3>
                     {insight.score && (
                       <span className={`text-xs font-bold px-2 py-0.5 rounded ${
                         insight.score > 70 ? 'bg-emerald-100 text-emerald-700' :
                         insight.score > 40 ? 'bg-amber-100 text-amber-700' :
                         'bg-red-100 text-red-700'
                       }`}>
                         Score: {insight.score}/100
                       </span>
                     )}
                   </div>
                   <p className="text-sm text-slate-600 leading-relaxed">{insight.content}</p>
                   <div className="pt-2 flex items-center gap-2">
                      <span className="text-xs text-slate-400 uppercase tracking-wider font-semibold">Entity: {insight.entityType}</span>
                   </div>
                 </div>
               </CardContent>
             </Card>
           ))}
        </div>
      )}
    </div>
  );
}
